"""
One-shot helper that derives runtime brand assets from the source PNGs.

Inputs (committed, do not edit):
  branding/armillarylab_classical.png  - gold-on-navy classical mark
  branding/armillarylab_appicon.png    - rounded-tile app icon

Outputs (regenerated by this script):
  static/img/logo.png   - chroma-keyed transparent-bg classical mark for navbar
  static/favicon.ico    - multi-resolution favicon derived from app-icon

  Run:  dev/Scripts/python.exe branding/_make_assets.py
"""
from __future__ import annotations

from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
BRANDING = ROOT / "branding"
STATIC = ROOT / "static"


def chroma_key_to_alpha(src: Image.Image, tolerance: int = 22, soft: int = 60) -> Image.Image:
    """Convert a solid-background image to RGBA by keying out the corner color.

    Pixels close to the sampled background colour become fully transparent;
    pixels far from it stay fully opaque, with a soft falloff so edges
    anti-alias naturally instead of producing a harsh outline.

    tolerance: max distance considered "fully background" (alpha = 0)
    soft:      additional distance over which alpha ramps from 0 to 255
    """
    rgba = src.convert("RGBA")
    px = rgba.load()
    w, h = rgba.size

    samples = [px[0, 0], px[w - 1, 0], px[0, h - 1], px[w - 1, h - 1]]
    br = sum(s[0] for s in samples) // len(samples)
    bg = sum(s[1] for s in samples) // len(samples)
    bb = sum(s[2] for s in samples) // len(samples)

    for y in range(h):
        for x in range(w):
            r, g, b, _a = px[x, y]
            dist = ((r - br) ** 2 + (g - bg) ** 2 + (b - bb) ** 2) ** 0.5
            if dist <= tolerance:
                alpha = 0
            elif dist >= tolerance + soft:
                alpha = 255
            else:
                alpha = int(255 * (dist - tolerance) / soft)
            px[x, y] = (r, g, b, alpha)

    return rgba


def trim_transparent(im: Image.Image, padding: int = 8) -> Image.Image:
    bbox = im.getbbox()
    if bbox is None:
        return im
    x0, y0, x1, y1 = bbox
    w, h = im.size
    x0 = max(0, x0 - padding)
    y0 = max(0, y0 - padding)
    x1 = min(w, x1 + padding)
    y1 = min(h, y1 + padding)
    return im.crop((x0, y0, x1, y1))


def build_navbar_logo() -> Path:
    src = Image.open(BRANDING / "armillarylab_classical.png")
    keyed = chroma_key_to_alpha(src, tolerance=24, soft=70)
    cropped = trim_transparent(keyed, padding=12)

    target_h = 256
    ratio = target_h / cropped.height
    target_w = max(1, int(round(cropped.width * ratio)))
    resized = cropped.resize((target_w, target_h), Image.LANCZOS)

    out = STATIC / "img" / "logo.png"
    out.parent.mkdir(parents=True, exist_ok=True)
    resized.save(out, format="PNG", optimize=True)
    return out


def build_favicon() -> Path:
    src = Image.open(BRANDING / "armillarylab_appicon.png").convert("RGBA")
    if src.width != src.height:
        side = min(src.size)
        left = (src.width - side) // 2
        top = (src.height - side) // 2
        src = src.crop((left, top, left + side, top + side))

    sizes = [(16, 16), (32, 32), (48, 48), (64, 64), (128, 128), (256, 256)]
    out = STATIC / "favicon.ico"
    out.parent.mkdir(parents=True, exist_ok=True)
    src.save(out, format="ICO", sizes=sizes)
    return out


if __name__ == "__main__":
    logo_path = build_navbar_logo()
    fav_path = build_favicon()
    print(f"navbar logo -> {logo_path.relative_to(ROOT)}")
    print(f"favicon     -> {fav_path.relative_to(ROOT)}")
